import fs from 'node:fs';
import path from 'node:path';
import { isCurrentRender } from './revision.js';
import { catalogue } from './catalogue.js';
import { outputRoot, readFilms } from './render.js';

const html = (s: string) => s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function writeGallery() {
  const films = readFilms([]).filter(f=>!f.preview);
  const entries = films.map(f=>({ready:isCurrentRender(f),id:f.skit.id,title:f.skit.title,kind:f.skit.kind,season:f.skit.season??'all',durationSeconds:f.durationInFrames/f.fps,video:`videos/${f.skit.id}.mp4`,captions:`videos/${f.skit.id}.vtt`,manifest:`manifests/${f.skit.id}.json`,synopsis:f.skit.synopsis,cast:f.skit.cast,languages:[...new Set(f.skit.lines.map(l=>l.language))],sources:f.skit.sources??[]}));
  fs.writeFileSync(path.join(outputRoot,'catalogue.json'),JSON.stringify({version:1,timezone:'Europe/Prague',seasonPolicy:'meteorological: March–May, June–August, September–November, December–February',entries},null,2));
  const cards=entries.map(e=>`<article data-kind="${e.kind}" data-season="${e.season}">${e.ready?`<video controls preload="none" poster="stills/${e.id}-${e.kind==='ident'?4:2}.png"><source src="${e.video}" type="video/mp4">${e.kind==='silent'?'':`<track kind="captions" label="Original dialogue" src="${e.captions}">`}</video>`:`<img class="poster" alt="${html(e.title)} preview" src="stills/${e.id}-${e.kind==='ident'?4:2}.png">`}<div class="copy"><div class="meta">${e.kind==='silent'?html(e.season):e.kind==='ident'?'CHANNEL IDENT':'DIALOGUE'} · ${e.durationSeconds.toFixed(1)} s</div><h2>${html(e.title)}</h2><p>${html(e.synopsis)}</p>${e.ready?`<a href="${e.video}" download>Download MP4 ↗</a>`:'<span>Final render pending</span>'}${e.kind==='silent'?'':` · <a href="videos/${e.id}.srt" download>Dialogue</a>`}</div></article>`).join('\n');
  fs.writeFileSync(path.join(outputRoot,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LKP · Intermissions, Set 1</title><style>
@font-face{font-family:Fredoka;src:url(brand/Fredoka.ttf)}*{box-sizing:border-box}body{margin:0;background:#fffcf4;color:#004f4f;font-family:Fredoka,system-ui,sans-serif}header,main{max-width:1400px;margin:auto;padding:32px}header{display:flex;align-items:center;gap:32px;padding-bottom:12px}header img{width:125px}h1{font-size:clamp(28px,4vw,48px);margin:0}header p{font-size:18px;line-height:1.5;margin:8px 0}.filters{display:flex;flex-wrap:wrap;gap:9px;margin:0 0 28px}button{font:inherit;font-size:16px;border:1px solid #004f4f;background:transparent;color:#004f4f;padding:9px 20px;border-radius:24px;cursor:pointer}button[aria-pressed=true]{background:#004f4f;color:#fff}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,370px),1fr));gap:24px}article{border:1px solid #cbdacf;border-radius:18px;overflow:hidden;background:#fff}video,.poster{display:block;width:100%;aspect-ratio:16/9;background:#e5f5f1}.copy{padding:22px}h2{font-size:27px;margin:8px 0}p{line-height:1.55;color:#506761}.meta{font-size:12px;letter-spacing:2px;text-transform:uppercase}a{color:#006c75}footer{padding:36px 0;color:#506761}[hidden]{display:none!important}</style>
<header><img src="brand/channel-icon.svg" alt="LKP"><div><h1>Little breaks. Big personalities.</h1><p>Intermissions · Set 1 · ${entries.length} films<br>Knurpsi, Sisi, Schalinka &amp; Haluschka</p></div></header><main>
<nav class="filters" aria-label="Filter films">${['All','Dialogue','Spring','Summer','Autumn','Winter'].map((s,i)=>`<button type="button" data-filter="${s.toLowerCase()}" aria-pressed="${i===0}">${s}</button>`).join('')}</nav>
<div class="grid">${cards}</div><footer><a href="brand/lkp-premium.svg" download>Download the new logo (SVG)</a> · <a href="catalogue.json">Film catalogue</a> · <a href="SCRIPTS.md">Dialogue &amp; sources</a><p>1920 × 1080 · 30 fps · Original character voices. Seasonal films contain Foley only.</p></footer></main>
<script>document.querySelectorAll('button[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('button[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('article').forEach(a=>{a.hidden=!(b.dataset.filter==='all'||(b.dataset.filter==='dialogue'&&a.dataset.kind!=='silent')||a.dataset.season===b.dataset.filter);if(a.hidden)a.querySelector('video')?.pause()})}));document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(o=>{if(o!==v)o.pause()})));</script></html>`);
  fs.copyFileSync('assets/weather/fonts/Fredoka.ttf',path.join(outputRoot,'brand/Fredoka.ttf'));
  fs.writeFileSync(path.join(outputRoot,'SCRIPTS.md'),'# LKP Intermissions — Set 1\n\n'+catalogue.map(s=>`## ${s.id} — ${s.title}\n\n${s.synopsis}\n\n${s.lines.map(l=>`**${l.speaker} (${l.language}):** ${l.text}`).join('\n\n')}\n\n${s.sources?.length?'Sources:\n'+s.sources.map(url=>`- ${url}`).join('\n'):''}`).join('\n\n'));
  console.log(`Gallery: ${path.join(outputRoot,'index.html')} (${entries.length} films)`);
}
